/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AsciiAnimationEmbed = {
  _type: "asciiAnimationEmbed";
  animation: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "asciiAnimation";
  };
  size?: "small" | "medium" | "large";
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote" | "figcaption";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  height?: number;
  width?: number;
  _type: "image";
  _key: string;
} | {
  _key: string;
} & AsciiAnimationEmbed | {
  _key: string;
} & Code>;

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  thumbnailAnimation?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "asciiAnimation";
  };
  body?: BlockContent;
};

export type AsciiAnimation = {
  _id: string;
  _type: "asciiAnimation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  animationType: "ascii-chip";
  preset?: "chip-default" | "chip-dark" | "chip-light";
  poster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  config?: {
    speed?: number;
    rotationPeriod?: number;
    grid?: {
      columns?: number;
      rows?: number;
    };
    character?: {
      width?: number;
      height?: number;
      fontSize?: number;
      fontFamily?: string;
    };
    colors?: {
      cyan?: string;
      teal?: string;
      gold?: string;
      edge?: string;
      substrate?: string;
      background?: string;
    };
    themeColors?: {
      dark?: {
        cyan?: string;
        teal?: string;
        gold?: string;
        edge?: string;
        substrate?: string;
        background?: string;
      };
      light?: {
        cyan?: string;
        teal?: string;
        gold?: string;
        edge?: string;
        substrate?: string;
        background?: string;
      };
    };
    chip?: {
      size?: number;
      thickness?: number;
      projectionScale?: number;
      cameraDistance?: number;
    };
  };
};

export type Projects = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cta?: string;
  title: string;
  body?: BlockContent;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cta?: string;
  title: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = AsciiAnimationEmbed | BlockContent | Project | AsciiAnimation | Projects | About | Home | Code | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(main)/about/page.tsx
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0]{    cta,    title,    body}
export type ABOUT_QUERYResult = {
  cta: string | null;
  title: string;
  body: BlockContent | null;
} | null;

// Source: ./app/(main)/page.tsx
// Variable: HOME_QUERY
// Query: *[_type == "home"][0]{  cta,  title,  body,}
export type HOME_QUERYResult = {
  cta: string | null;
  title: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ./app/(main)/projects/[slug]/page.tsx
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  _id,  title,  slug,  thumbnail,  thumbnailAnimation->{    _id,    title,    animationType,    config,    poster  },  body[]{    ...,    _type == "asciiAnimationEmbed" => {      ...,      animation->{        _id,        title,        animationType,        config,        poster      }    }  }}
export type PROJECT_QUERYResult = {
  _id: string;
  title: string;
  slug: Slug;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  thumbnailAnimation: {
    _id: string;
    title: string;
    animationType: "ascii-chip";
    config: {
      speed?: number;
      rotationPeriod?: number;
      grid?: {
        columns?: number;
        rows?: number;
      };
      character?: {
        width?: number;
        height?: number;
        fontSize?: number;
        fontFamily?: string;
      };
      colors?: {
        cyan?: string;
        teal?: string;
        gold?: string;
        edge?: string;
        substrate?: string;
        background?: string;
      };
      themeColors?: {
        dark?: {
          cyan?: string;
          teal?: string;
          gold?: string;
          edge?: string;
          substrate?: string;
          background?: string;
        };
        light?: {
          cyan?: string;
          teal?: string;
          gold?: string;
          edge?: string;
          substrate?: string;
          background?: string;
        };
      };
      chip?: {
        size?: number;
        thickness?: number;
        projectionScale?: number;
        cameraDistance?: number;
      };
    } | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  body: Array<{
    _key: string;
    _type: "asciiAnimationEmbed";
    animation: {
      _id: string;
      title: string;
      animationType: "ascii-chip";
      config: {
        speed?: number;
        rotationPeriod?: number;
        grid?: {
          columns?: number;
          rows?: number;
        };
        character?: {
          width?: number;
          height?: number;
          fontSize?: number;
          fontFamily?: string;
        };
        colors?: {
          cyan?: string;
          teal?: string;
          gold?: string;
          edge?: string;
          substrate?: string;
          background?: string;
        };
        themeColors?: {
          dark?: {
            cyan?: string;
            teal?: string;
            gold?: string;
            edge?: string;
            substrate?: string;
            background?: string;
          };
          light?: {
            cyan?: string;
            teal?: string;
            gold?: string;
            edge?: string;
            substrate?: string;
            background?: string;
          };
        };
        chip?: {
          size?: number;
          thickness?: number;
          projectionScale?: number;
          cameraDistance?: number;
        };
      } | null;
      poster: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    };
    size?: "large" | "medium" | "small";
  } | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "figcaption" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "code";
    language?: string;
    filename?: string;
    code?: string;
    highlightedLines?: Array<number>;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    height?: number;
    width?: number;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Source: ./app/(main)/projects/page.tsx
// Variable: PROJECTS_QUERY
// Query: *[_type == "projects"][0]{  title,  body,  projects[]->{    _type,    _id,    title,    slug,    thumbnail,    thumbnailAnimation->{      _id,      title,      animationType,      config,      poster    },    body[]{      ...,      _type == "asciiAnimationEmbed" => {        ...,        animation->{          _id,          title,          animationType,          config,          poster        }      }    }  }}
export type PROJECTS_QUERYResult = {
  title: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  projects: Array<{
    _type: "project";
    _id: string;
    title: string;
    slug: Slug;
    thumbnail: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    thumbnailAnimation: {
      _id: string;
      title: string;
      animationType: "ascii-chip";
      config: {
        speed?: number;
        rotationPeriod?: number;
        grid?: {
          columns?: number;
          rows?: number;
        };
        character?: {
          width?: number;
          height?: number;
          fontSize?: number;
          fontFamily?: string;
        };
        colors?: {
          cyan?: string;
          teal?: string;
          gold?: string;
          edge?: string;
          substrate?: string;
          background?: string;
        };
        themeColors?: {
          dark?: {
            cyan?: string;
            teal?: string;
            gold?: string;
            edge?: string;
            substrate?: string;
            background?: string;
          };
          light?: {
            cyan?: string;
            teal?: string;
            gold?: string;
            edge?: string;
            substrate?: string;
            background?: string;
          };
        };
        chip?: {
          size?: number;
          thickness?: number;
          projectionScale?: number;
          cameraDistance?: number;
        };
      } | null;
      poster: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
    body: Array<{
      _key: string;
      _type: "asciiAnimationEmbed";
      animation: {
        _id: string;
        title: string;
        animationType: "ascii-chip";
        config: {
          speed?: number;
          rotationPeriod?: number;
          grid?: {
            columns?: number;
            rows?: number;
          };
          character?: {
            width?: number;
            height?: number;
            fontSize?: number;
            fontFamily?: string;
          };
          colors?: {
            cyan?: string;
            teal?: string;
            gold?: string;
            edge?: string;
            substrate?: string;
            background?: string;
          };
          themeColors?: {
            dark?: {
              cyan?: string;
              teal?: string;
              gold?: string;
              edge?: string;
              substrate?: string;
              background?: string;
            };
            light?: {
              cyan?: string;
              teal?: string;
              gold?: string;
              edge?: string;
              substrate?: string;
              background?: string;
            };
          };
          chip?: {
            size?: number;
            thickness?: number;
            projectionScale?: number;
            cameraDistance?: number;
          };
        } | null;
        poster: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      };
      size?: "large" | "medium" | "small";
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "figcaption" | "h1" | "h2" | "h3" | "h4" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      _key: string;
      _type: "code";
      language?: string;
      filename?: string;
      code?: string;
      highlightedLines?: Array<number>;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      height?: number;
      width?: number;
      _type: "image";
      _key: string;
    }> | null;
  }> | null;
} | null;

// Source: ./app/api/ascii/thumbnail/route.ts
// Variable: ASCII_QUERY
// Query: *[_type == "asciiAnimation" && _id == $id][0]{  _id,  animationType,  preset,  config}
export type ASCII_QUERYResult = {
  _id: string;
  animationType: "ascii-chip";
  preset: "chip-dark" | "chip-default" | "chip-light" | null;
  config: {
    speed?: number;
    rotationPeriod?: number;
    grid?: {
      columns?: number;
      rows?: number;
    };
    character?: {
      width?: number;
      height?: number;
      fontSize?: number;
      fontFamily?: string;
    };
    colors?: {
      cyan?: string;
      teal?: string;
      gold?: string;
      edge?: string;
      substrate?: string;
      background?: string;
    };
    themeColors?: {
      dark?: {
        cyan?: string;
        teal?: string;
        gold?: string;
        edge?: string;
        substrate?: string;
        background?: string;
      };
      light?: {
        cyan?: string;
        teal?: string;
        gold?: string;
        edge?: string;
        substrate?: string;
        background?: string;
      };
    };
    chip?: {
      size?: number;
      thickness?: number;
      projectionScale?: number;
      cameraDistance?: number;
    };
  } | null;
} | null;

// Source: ./app/sitemap.ts
// Variable: PROJECTS_QUERY_SITEMAP
// Query: *[_type == "projects"][0]{    title,    body,    projects[]->{      _type,      _id,      title,      slug,      thumbnail,      body    }  }
export type PROJECTS_QUERY_SITEMAPResult = {
  title: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  projects: Array<{
    _type: "project";
    _id: string;
    title: string;
    slug: Slug;
    thumbnail: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    body: BlockContent | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"about\"][0]{\n    cta,\n    title,\n    body\n}": ABOUT_QUERYResult;
    "*[_type == \"home\"][0]{\n  cta,\n  title,\n  body,\n}": HOME_QUERYResult;
    "*[_type == \"project\" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  thumbnail,\n  thumbnailAnimation->{\n    _id,\n    title,\n    animationType,\n    config,\n    poster\n  },\n  body[]{\n    ...,\n    _type == \"asciiAnimationEmbed\" => {\n      ...,\n      animation->{\n        _id,\n        title,\n        animationType,\n        config,\n        poster\n      }\n    }\n  }\n}": PROJECT_QUERYResult;
    "*[_type == \"projects\"][0]{\n  title,\n  body,\n  projects[]->{\n    _type,\n    _id,\n    title,\n    slug,\n    thumbnail,\n    thumbnailAnimation->{\n      _id,\n      title,\n      animationType,\n      config,\n      poster\n    },\n    body[]{\n      ...,\n      _type == \"asciiAnimationEmbed\" => {\n        ...,\n        animation->{\n          _id,\n          title,\n          animationType,\n          config,\n          poster\n        }\n      }\n    }\n  }\n}": PROJECTS_QUERYResult;
    "*[_type == \"asciiAnimation\" && _id == $id][0]{\n  _id,\n  animationType,\n  preset,\n  config\n}": ASCII_QUERYResult;
    "*[_type == \"projects\"][0]{\n    title,\n    body,\n    projects[]->{\n      _type,\n      _id,\n      title,\n      slug,\n      thumbnail,\n      body\n    }\n  }": PROJECTS_QUERY_SITEMAPResult;
  }
}
