import type { Metadata } from "next";
import { Geist, Geist_Mono, Oxanium, JetBrains_Mono } from "next/font/google";

const geist = Geist({ subsets: ["latin"], adjustFontFallback: false });
const geistMono = Geist_Mono({ subsets: ["latin"], adjustFontFallback: false, variable: "--geistMono" });

const tempFont = Oxanium({ subsets: ["latin"], adjustFontFallback: false });
const tempMono = JetBrains_Mono({ subsets: ["latin"], adjustFontFallback: false, variable: "--jetbrainsMono" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            {/* <body className={`${geist.className} ${geistMono.variable}`}> */}
            <body className={`${tempFont.className} ${tempMono.variable}`}>
                {children}
            </body>
        </html>
    );
}
