import type { Metadata } from "next";
import "./globals.css";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/utils/theme-provider";
import Navbar from "@/components/navbar";

const geist = Geist({ subsets: ["latin"], adjustFontFallback: false });
const geistMono = Geist_Mono({ subsets: ["latin"], adjustFontFallback: false, variable: "--geistMono" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geist.className} ${geistMono.variable}`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<Navbar />
					{children}
					<SanityLive />
					{(await draftMode()).isEnabled && <VisualEditing />}
				</ThemeProvider>
			</body>
		</html>
	);
}
